approx_rec_pos:
- 0.0
- 0.0
- 0.0
eph_settings:
  baudrate: 115200
  databits: 8
  enabled: true
  flowctrl: None
  host: ntrip.data.gnss.ga.gov.au
  mountpoint: BCEP00BKG0
  parity: None
  password: Hao20030801@
  port: '2101'
  serial_port: COM3
  source_type: NTRIP Server
  stopbits: 1.0
  user: hrx
obs_settings:
  baudrate: 115200
  databits: 8
  enabled: true
  flowctrl: None
  host: ntrip.data.gnss.ga.gov.au
  mountpoint: BRST00FRA0
  parity: None
  password: Hao20030801@
  port: '2101'
  serial_port: COM3
  source_type: NTRIP Server
  stopbits: 1.0
  user: hrx
positioning_settings:
  cutoff_elevation_deg: 10.0
  fixed_std_pos: 2.5
  gnss_systems:
  - G
  - R
  - E
  - C
  - J
  - I
  ionosphere_option: IFLC
  max_pdop: 10.0
  min_satellites: 4
  random_walk: 0.0
  smoothing_window: 10
  troposphere_model: Sastamoinen
  uncertain_std_pos: 5.0
  use_smoothing: false
  weight_mode: elevation
target_systems:
- G
- R
- E
- C
- J
- S
- I
