approx_rec_pos: null
eph_settings:
  baudrate: 115200
  databits: 8
  enabled: false
  file_path: ''
  file_type: Auto Detect
  final_results_only: false
  flowctrl: None
  host: ''
  mountpoint: ''
  parity: None
  password: ''
  port: '2101'
  replay_speed: 1.0
  serial_port: COM1
  source_type: NTRIP Server
  stopbits: 1
  user: ''
obs_settings:
  baudrate: 115200
  databits: 8
  enabled: true
  file_path: ''
  file_type: Auto Detect
  final_results_only: false
  flowctrl: None
  host: ntrip.geodetic.gov.hk
  mountpoint: HKQT_32
  parity: None
  password: ''
  port: '2101'
  replay_speed: 1.0
  serial_port: COM14
  source_type: NTRIP Server
  stopbits: 1.0
  user: ''
positioning_settings:
  cutoff_elevation_deg: 10.0
  fixed_std_pos: 2.5
  gnss_systems:
  - G
  - R
  - E
  - C
  - J
  - I
  ionosphere_option: IFLC
  max_pdop: 10.0
  min_satellites: 4
  random_walk: 0.0
  smoothing_window: 10
  troposphere_model: Sastamoinen
  uncertain_std_pos: 5.0
  use_smoothing: false
  weight_mode: elevation
target_systems:
- G
- R
- E
- C
- J
- S
- I
