approx_rec_pos: null
eph_settings:
  baudrate: 115200
  databits: 8
  enabled: true
  file_path: ''
  file_type: Auto Detect
  final_results_only: false
  flowctrl: None
  host: ntrip.data.gnss.ga.gov.au
  mountpoint: BCEP00BKG0
  parity: None
  password: Hao20030801@
  port: '2101'
  replay_speed: 1.0
  serial_port: /dev/ttyS31
  source_type: NTRIP Server
  stopbits: 1.0
  user: hrx
obs_settings:
  baudrate: 115200
  databits: 8
  enabled: true
  file_path: ''
  file_type: Auto Detect
  final_results_only: false
  flowctrl: None
  host: grserg.top
  mountpoint: XHBD
  parity: None
  password: hao20030801
  port: '2101'
  replay_speed: 1.0
  serial_port: /dev/ttyS31
  source_type: NTRIP Server
  stopbits: 1.0
  user: adminHRX
positioning_settings:
  allow_gps_fallback: false
  code_sigma_m: 1.0
  cutoff_elevation_deg: 10.0
  fixed_std_pos: 2.5
  gnss_systems:
  - G
  - R
  - E
  - C
  - J
  - I
  ionosphere_option: IFLC
  max_pdop: 10.0
  min_satellites: 4
  ppp_initial_ambiguity_sigma_m: 1000.0
  ppp_initial_clock_sigma_m: 1000.0
  ppp_position_process_noise_mps: 0.0
  ppp_station_apriori_sigma_m: 0.05
  ppp_trop_process_noise_mps: 3.0e-06
  ppp_use_station_apriori: false
  prefer_gps_only: false
  random_walk: 0.0
  require_ssr_corrections: true
  smoothing_window: 10
  system_code_weight_factors:
    R: 5.0
  troposphere_model: Sastamoinen
  uncertain_std_pos: 5.0
  use_smoothing: false
  weight_mode: elevation
ssr_settings:
  baudrate: 115200
  databits: 8
  enabled: true
  file_path: ''
  file_type: Auto Detect
  final_results_only: false
  flowctrl: None
  host: ntrip.data.gnss.ga.gov.au
  mountpoint: SSRA00CAS0
  parity: None
  password: Hao20030801@
  port: '2101'
  replay_speed: 1.0
  serial_port: /dev/ttyS31
  source_type: NTRIP Server
  stopbits: 1.0
  user: hrx
target_systems:
- G
- R
- E
- C
- J
- S
- I
